default_platform(:android)

platform :android do
  desc "Deploy a new version to the Google Play Store (Internal Test)"
  lane :deploy_alpha do
    gradle(task: "clean bundleRelease")
    upload_to_play_store(
      track: "internal",
      aab: "app/build/outputs/bundle/release/app-release.aab",
      skip_upload_metadata: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
